version: '3.4'

networks:
  dev:
    driver: bridge

services:
  shortener-api:
    image: docker.io/library/shortenerapi
    depends_on:
      - "app_db"
    container_name: shortenerapi-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Database=User ID=postgres;Password=5456;Server=app_db;Port=5432;Database=shortener;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development 
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5456
      - POSTGRES_DB=shortener
    ports:
      - "5433:5432"
    restart: always
    volumes:
     - app_data:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data:  
  